const mongoose = require('mongoose');

const orderSchema = mongoose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true
        },
        phoneNo:{
            type:Number,
            required:true
        }
    },
    orderItem:[
        {
            name:{
                type:String,
                required:true
            },
            price:{
                type:Number,
                required:true
            },
            quantity:{
                type:Number,
                required:true
            },
            product:{
                type:mongoose.Schema.ObjectID,
                ref:"Product",
                required:true
            },
        }
    ],
    user:{
        type:mongoose.Schema.ObjectID,
        ref:"User",
        required:true
    },
    paymentInfo:{
        id:{
            type:String,
            required:true
        },
        status:{
            type:String,
            required:true
        },

    },
    paidAt:{
        type:Date,
    },
    itemPrice:{
        type:Number,
        required:true,
        default:0
    },
    taxPrice:{
        type:Number,
        required:true,
        default:0
    },
    shippingPrice:{
        type:Number,
        required:true,
        default:0
    },
    totalPrice:{
        type:Number,
        required:true,
        default:0
    },
    orderStatus:{
        type:String,
        required:true,
        default:"Processing"
    },
    deliveryDate:Date,
    createdAt:{
        type:Date,
        default:new Date()
    }
});

const Order=mongoose.model("Order",orderSchema);
module.exports=Order